name: Update All Games

on:
  repository_dispatch:
    types: [update-all-games]

jobs:
  update-all-games:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch all Game submodules

      - name: Update all game submodules
        run: git submodule foreach git pull origin gh-pages

      - name: Commit new updates
        run: |
          git add .
          git commit -m "Updating published games"
          git push
