name: Deploy Games

on:
  push:
    branches:
      # And only on main branch
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # Specify all desired node versions
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: List Games
      #   run: cd games && list games

      - name: Open Cellar Crawl
        run: |
          pwd
          cd games/cellar-crawl
          pwd

      - name: Spindle Build
        run: |
          pwd
          games/cellar-crawl
          yarn install
          yarn run spindle
          cd ../..

      - name: Prepare Deploy Package
        run: |
          mkdir dist
          mv games/cellar-crawl/output/cellar-crawl.html dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: dist      # The folder the action should deploy.
