name: Update All Games
# Triggered by a repo_dispatch from sub repo. Update all submodules and commit to main

on:
  repository_dispatch:
    types: [update-all-games]

jobs:
  update-all-games:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch all Game submodules

      - name: Update all game submodules
        run: git submodule foreach git pull --ff-only origin gh-pages

      - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          # The flag used on the pull strategy
          pull_strategy: '--no-ff'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
